# Generated by Django 5.0.6 on 2025-01-12 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_comment_note_testmodel_testtype_userstatistics_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='title',
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.CreateModel(
            name='TestDownloadStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_count', models.IntegerField(default=0)),
                ('xml_count', models.IntegerField(default=0)),
                ('json_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]



