# Generated by Django 5.0.6 on 2024-06-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyuka', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priloha',
            old_name='film',
            new_name='material',
        ),
    ]
