# Generated by Django 5.0.6 on 2024-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyuka', '0002_rename_film_priloha_material'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='plot',
            new_name='obsah',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='genres',
            new_name='predmet',
        ),
        migrations.RemoveField(
            model_name='material',
            name='poster',
        ),
        migrations.AddField(
            model_name='material',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='material/obsah/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
