# Generated by Django 5.0.6 on 2024-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vyuka', '0003_rename_plot_material_obsah_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-release_date', 'title'], 'verbose_name': 'Výukový materiál', 'verbose_name_plural': 'Výukové materiály'},
        ),
    ]
