# Generated by Django 5.0.6 on 2024-06-09 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vyuka', '0004_alter_material_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='release_date',
            field=models.DateField(blank=True, help_text='Zadej datum vydání textu: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Vydání textu'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('text', models.TextField(verbose_name='Text')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Datum vytvoření')),
                ('approved', models.BooleanField(default=False, verbose_name='Schváleno')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vyuka.material')),
            ],
            options={
                'verbose_name': 'Komentář',
                'verbose_name_plural': 'Komentáře',
                'ordering': ['-created_date'],
            },
        ),
    ]
